name: typecast
description: Digest aggregator for 4PDA
publish_to: 'none'
version: 2.2.1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flex_color_scheme: ^7.0.4
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_linkify: ^5.0.2
  flutter_localizations:
    sdk: flutter
  http: ^0.13.5
  intl: any
  shared_preferences: ^2.1.0
  url_launcher: ^6.1.10
  windows1251: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Comic Sans MS
      fonts:
        - asset: fonts/comic.ttf

flutter_launcher_icons:
  android: false
  ios: true
  image_path: "assets/icon/icon.png"
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icon/icon.png"
